-- Corrige l'insertion depuis QField/QFieldCloud vers PostgreSQL.
--
-- Probleme : le fournisseur PostgreSQL de QGIS inclut TOUJOURS la colonne cle
-- dans son INSERT, avec la valeur NULL pour une entite creee sur le terrain.
-- Comme `qgis_id` est GENERATED ALWAYS AS IDENTITY, PostgreSQL refuse :
--   ERREUR: ne peut pas inserer une valeur pas par defaut dans la colonne « qgis_id »
-- Les UPDATE et DELETE, eux, fonctionnent (WHERE qgis_id = ...).
--
-- Correctif en deux temps :
--   1. l'identite passe de GENERATED ALWAYS a GENERATED BY DEFAULT
--      (accepte qu'une valeur soit fournie, mais refuse toujours NULL) ;
--   2. un trigger BEFORE INSERT remplace le NULL envoye par QGIS par la
--      valeur suivante de la sequence, avant le controle NOT NULL.
--
-- Idempotent : peut etre rejoue sans dommage.
-- Pour annuler :
--   DROP TRIGGER trg_qgis_id ON <schema>.<table>;              -- par table
--   ALTER TABLE <schema>.<table> ALTER COLUMN qgis_id SET GENERATED ALWAYS;
--   DROP FUNCTION ifa_qfield.qgis_id_defaut();

BEGIN;

CREATE SCHEMA IF NOT EXISTS ifa_qfield;

CREATE OR REPLACE FUNCTION ifa_qfield.qgis_id_defaut() RETURNS trigger
LANGUAGE plpgsql AS $f$
BEGIN
  IF NEW.qgis_id IS NULL THEN
    NEW.qgis_id := nextval(
      pg_get_serial_sequence(TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME, 'qgis_id'));
  END IF;
  RETURN NEW;
END $f$;

DO $$
DECLARE
  r record;
  n int := 0;
BEGIN
  FOR r IN
    SELECT ns.nspname AS sch, cl.relname AS tbl
    FROM pg_attribute a
    JOIN pg_class cl ON cl.oid = a.attrelid
    JOIN pg_namespace ns ON ns.oid = cl.relnamespace
    WHERE a.attname = 'qgis_id'
      AND NOT a.attisdropped
      AND cl.relkind = 'r'
      AND ns.nspname IN ('ifa_data', 'ifa_structure')
    ORDER BY 1, 2
  LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I ALTER COLUMN qgis_id SET GENERATED BY DEFAULT', r.sch, r.tbl);
    EXECUTE format(
      'DROP TRIGGER IF EXISTS trg_qgis_id ON %I.%I', r.sch, r.tbl);
    EXECUTE format(
      'CREATE TRIGGER trg_qgis_id BEFORE INSERT ON %I.%I '
      'FOR EACH ROW EXECUTE FUNCTION ifa_qfield.qgis_id_defaut()', r.sch, r.tbl);
    n := n + 1;
  END LOOP;
  RAISE NOTICE 'tables traitees : %', n;
END $$;

COMMIT;
